DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (

ID INT NOT NULL AUTO INCREMENT
 ,FIRST_NAME VARCHAR(6O) NOT NULL
 ,LAST_NAME VARCHAR(40) NOT NULL
 ,BIRTH
 DATE DATE ,DESCRIPTION VARCHAR(2000)
 ,PHOTO BLOB
 ,VERSION INT NOT NULL DEFAULT 0
 ,UNIQUE UQ_CONTACT_l (FIRST NAME, LAST_NAME)
 ,PRIMARY KEY (ID)

)；